# Generated by Django 5.2.12 on 2026-04-03 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('ms_established', models.CharField(default='LU', max_length=10)),
                ('competent_authority', models.CharField(blank=True, max_length=100)),
                ('misp_instance_url', models.URLField(blank=True)),
                ('misp_api_key', models.CharField(blank=True, max_length=255)),
                ('misp_default_tlp', models.CharField(default='tlp:amber', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('description', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('ms_affected', models.JSONField(blank=True, default=list)),
                ('service_impact', models.CharField(default='none', max_length=30)),
                ('data_impact', models.CharField(default='none', max_length=30)),
                ('safety_impact', models.CharField(default='none', max_length=30)),
                ('financial_impact', models.CharField(default='none', max_length=30)),
                ('affected_persons_count', models.IntegerField(default=0)),
                ('impact_duration_hours', models.IntegerField(default=0)),
                ('suspected_malicious', models.BooleanField(default=False)),
                ('physical_access_breach', models.BooleanField(default=False)),
                ('sector_specific', models.JSONField(blank=True, default=dict)),
                ('result_significance', models.BooleanField(blank=True, null=True)),
                ('result_significance_label', models.CharField(blank=True, max_length=30)),
                ('result_model', models.CharField(blank=True, max_length=50)),
                ('result_criteria', models.JSONField(blank=True, default=list)),
                ('result_framework', models.CharField(blank=True, max_length=50)),
                ('result_competent_authority', models.CharField(blank=True, max_length=100)),
                ('result_early_warning', models.JSONField(blank=True, default=dict)),
                ('result_raw', models.JSONField(blank=True, default=dict)),
                ('misp_event_uuid', models.CharField(blank=True, max_length=36)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='entity.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(choices=[('pdf_download', 'PDF Download'), ('misp_json_download', 'MISP JSON Download'), ('misp_push', 'MISP Push')], max_length=30)),
                ('misp_event_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='entity.assessment')),
            ],
        ),
    ]
