# Generated by Django 5.2.12 on 2026-04-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='affected_entity_types',
            field=models.JSONField(blank=True, default=list, help_text='List of {"sector": "...", "entity_type": "..."} dicts'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_results',
            field=models.JSONField(blank=True, default=list, help_text='Per-entity-type assessment results'),
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_types', to='entity.entity')),
            ],
            options={
                'ordering': ['sector', 'entity_type'],
                'unique_together': {('entity', 'entity_type')},
            },
        ),
    ]
