# Generated by Django 5.2.12 on 2026-04-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_populate_entity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='per_type_impacts',
            field=models.JSONField(blank=True, default=list, help_text='Per-entity-type impact data (ms_affected, impacts, sector_specific per type)'),
        ),
    ]
