# Generated by Django 5.2.12 on 2026-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_backfill_per_type_impacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='entity',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='entity',
            name='ip_ranges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='entity',
            name='misp_profile_event_uuid',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='entity',
            name='ms_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='entity',
            name='responsible_person_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='entity',
            name='responsible_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='technical_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='entity',
            name='technical_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entity',
            name='technical_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='target',
            field=models.CharField(choices=[('pdf_download', 'PDF Download'), ('misp_json_download', 'MISP JSON Download'), ('misp_push', 'MISP Push'), ('misp_profile_push', 'MISP Profile Push')], max_length=30),
        ),
    ]
