# Generated by Django 5.2.12 on 2026-04-04 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_art27_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='ca_auto_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='csirt_auto_assigned',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CompetentAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=20)),
                ('ms', models.CharField(max_length=10)),
                ('sectors', models.JSONField(default=list)),
                ('website', models.URLField(blank=True)),
                ('notification_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('receives_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'competent authorities',
                'unique_together': {('abbreviation', 'ms')},
            },
        ),
        migrations.AddField(
            model_name='entitytype',
            name='competent_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_types', to='entity.competentauthority'),
        ),
        migrations.CreateModel(
            name='CSIRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=20)),
                ('ms', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True)),
                ('notification_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=50)),
                ('receives_notifications', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CSIRT',
                'verbose_name_plural': 'CSIRTs',
                'unique_together': {('abbreviation', 'ms')},
            },
        ),
        migrations.AddField(
            model_name='entitytype',
            name='csirt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_types', to='entity.csirt'),
        ),
    ]
