# Generated by Django 5.2.12 on 2026-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_authority_csirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='cer_designated',
            field=models.BooleanField(default=False, help_text='Designated as critical entity under CER Directive'),
        ),
    ]
