# Generated by Django 5.2.12 on 2026-04-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_cer_designated'),
    ]

    operations = [
        migrations.AddField(
            model_name='csirt',
            name='cer_only',
            field=models.BooleanField(default=False, help_text='Also serves CER-designated entities regardless of sector'),
        ),
        migrations.AddField(
            model_name='csirt',
            name='sectors',
            field=models.JSONField(default=list, help_text='Sectors served (["*"] = all, ["public_administration"] = specific)'),
        ),
    ]
